### ISSUE TITLE
ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by ldavidsp** [AlexTorresSk/custom-electron-titlebar#158]
A JavaScript error occurred in the main process
Uncaught Exception:
ReferenceError: `navigator` is not defined
```
node_modules/custom-electron-titlebar/browser/browser.js:131:19)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12789)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)

```

**Comment by ericblade** [comment]
looks like you're trying to load it in your main not in your renderer.
