### ISSUE TITLE
 ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by ivictbor** [AlexTorresSk/custom-electron-titlebar#51]
Thx for project!
Only followed steps from readme
```
  ReferenceError: navigator is not defined
      at Object.<anonymous> (C:xxx\app\node_modules\custom-electron-titlebar\lib\browser\browser.js:130:19)
      at Module._compile (internal/modules/cjs/loader.js:786:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
      at Module.load (internal/modules/cjs/loader.js:645:32)
      at Function.Module._load (internal/modules/cjs/loader.js:560:12)
      at Module.require (internal/modules/cjs/loader.js:685:19)
      at require (internal/modules/cjs/helpers.js:16:16)
      at Object.<anonymous> (C:\xxx\app\node_modules\custom-electron-titlebar\lib\common\dom.js:7:17)
      at Module._compile (internal/modules/cjs/loader.js:786:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
```

` "electron": "^6.0.2",`

**Comment by ivictbor** [comment]
got it, this plugin for render thread, not for main window. Though might be helfull to state it somewhere in doc, or show readable error (or maybe just missed)

**Comment by ivanjeremic** [comment]
I got the same error when trying to add the titlebar in the Main.js of electron (where the whole electron stuff goes). Instead, I added the titlebar in the index.html at the end of the body tag in a script tag.
