### ISSUE TITLE
TypeError: Cannot read property 'getElementsByClassName' of null

### ISSUE THREAD

**Issue by koostamas** [AlexTorresSk/custom-electron-titlebar#69]
I am trying to add this to an existing electron app. I added this code to the beginning of browser.ts:
```
new Titlebar({
	backgroundColor: Color.fromHex('#000000')
});
```
But when I run the app I get the following error:
```
TypeError: Cannot read property 'getElementsByClassName' of null
    at _applyRules (G:\Development\web\caprine\node_modules\custom-electron-titlebar\lib\themebar.js:528:37)
    at Titlebar.registerTheme (G:\Development\web\caprine\node_modules\custom-electron-titlebar\lib\themebar.js:367:9)
    at new Themebar (G:\Development\web\caprine\node_modules\custom-electron-titlebar\lib\themebar.js:32:14)
    at new Titlebar (G:\Development\web\caprine\node_modules\custom-electron-titlebar\lib\titlebar.js:39:9)
    at Object.<anonymous> (G:\Development\web\caprine\dist-js\browser.js:15:1)
    at Object.<anonymous> (G:\Development\web\caprine\dist-js\browser.js:556:3)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
(anonymous) @ electron/js2c/renderer_init.js:2533
```
Apparently document.head is null. What can I do to solve this issue?

**Comment by koostamas** [comment]
So as it turns out, I was trying to add the Titlebar too early. I solved this by listening to the `DOMContentLoaded` event and adding the Titlebar then.
